{"uuid": "af634599-6816-4fe6-b128-a41037da17ff", "children": ["eef8db9f-f3d0-423e-b3fd-40058f862333"], "befores": [{"name": "setup_login_uno", "status": "passed", "start": 1630008725154, "stop": 1630008731826}], "afters": [{"name": "setup_login_uno::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"c:\\users\\usuario1\\documents\\practicas_udemy\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\usuario1\\documents\\practicas_udemy\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Usuario1\\Documents\\PRACTICAS_UDEMY\\Maquina_uno\\MV1\\PYTEST\\Fixture_decorate2.py\", line 42, in setup_login_uno\n    driver.close()\n  File \"c:\\users\\usuario1\\documents\\practicas_udemy\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"c:\\users\\usuario1\\documents\\practicas_udemy\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\usuario1\\documents\\practicas_udemy\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1630008756761, "stop": 1630008756862}], "start": 1630008725154, "stop": 1630008756862}